# 모델설계하기
---

# 1. data import

## 1-1. read & check

In [4]:
import pandas as pd
from google.colab import drive # 드라이브에서 파일 가져오는 방식
drive.mount("/content/drive")

filename = "/content/drive/MyDrive/Deeplearning/datasets/diabetes.csv"
df = pd.read_csv(filename, header=None, names = ["pregnant",'plasma','pressure','thickness','insulin', 'BMI','pedigree','age','class'])
df.head(3)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,pregnant,plasma,pressure,thickness,insulin,BMI,pedigree,age,class
0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,6,148,72,35,0,33.6,0.627,50,1
2,1,85,66,29,0,26.6,0.351,31,0

In [6]:
df.describe()

       pregnant plasma pressure thickness insulin  BMI pedigree  age class
count       769    769      769       769     769  769      769  769   769
unique       18    137       48        52     187  249      518   53     3
top           1    100       70         0       0   32    0.254   22     0
freq        135     17       57       227     374   13        6   72   500

In [8]:
df.info() # 다 object임

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 769 entries, 0 to 768
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pregnant   769 non-null    object
 1   plasma     769 non-null    object
 2   pressure   769 non-null    object
 3   thickness  769 non-null    object
 4   insulin    769 non-null    object
 5   BMI        769 non-null    object
 6   pedigree   769 non-null    object
 7   age        769 non-null    object
 8   class      769 non-null    object
dtypes: object(9)
memory usage: 54.2+ KB

In [9]:
df.iloc[:, -1].unique()

array(['Outcome', '1', '0'], dtype=object)

![](2022-11-03-10-16-51.png)

![](2022-11-03-10-17-44.png)